version: '3'

services:
    composer:
        image: composer:2.4.2
        volumes:
            - composer-cache:/tmp
            - ./:/app
        working_dir: /app
        command: composer install

volumes:
    composer-cache:
        driver: local
